# Generated by Django 3.2.7 on 2021-09-24 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('prioridade', models.PositiveIntegerField(choices=[(1, 'Alta'), (2, 'Média'), (3, 'Baixa')], verbose_name='Prioridade')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefas.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
