# Generated by Django 3.2.7 on 2021-10-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_tarefas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='status',
            field=models.CharField(choices=[('AF', 'A Fazer'), ('PD', 'Pendente'), ('CD', 'Concluída')], default='AF', max_length=2, verbose_name='Status'),
        ),
    ]
